Note!!! - The process of getting the bounding box text files in the correct format is incomlete.
The major drawback is that there is only one bounding box defined per image, while some of them have multiple logos (of the same company only)

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
%cd drive/My\ Drive/LogoDetection/
#go to appropriate directory in drive - Here, LogoDetection/allMasks contains the unprocessed text files of the bounding boxes.
#They have been copied into one folder (allMasks) without changing their names to maintain alphabetical ordering...
#This notebook will rewrite them with the correct parameters and rename them appropriately...

/content/drive/My Drive/LogoDetection


In [0]:
import os
import numpy as np
import cv2
import matplotlib.pyplot as plt

In [11]:
%cd /
%cd content/drive/My\ Drive/LogoDetection/allImages

/
/content/drive/My Drive/LogoDetection/allImages


In [13]:
#Rename all the image files to lower case so as to maintain alphabetical ordering...

%cd /
%cd content/drive/My\ Drive/LogoDetection/allImages

cnt = 0
for fil in sorted(os.listdir()):

  if fil.endswith('.jpg'):
    name = fil.lower()
    os.rename(fil, name)
    cnt += 1

print(cnt)
assert (cnt == 700)

adidas1.jpg
adidas10.jpg
adidas11.jpg
adidas12.jpg
adidas13.jpg
adidas14.jpg
adidas15.jpg
adidas16.jpg
adidas17.jpg
adidas18.jpg
adidas19.jpg
adidas2.jpg
adidas20.jpg
adidas21.jpg
adidas22.jpg
adidas23.jpg
adidas24.jpg
adidas25.jpg
adidas26.jpg
adidas27.jpg
adidas28.jpg
adidas29.jpg
adidas3.jpg
adidas30.jpg
adidas31.jpg
adidas32.jpg
adidas33.jpg
adidas34.jpg
adidas35.jpg
adidas36.jpg
adidas37.jpg
adidas38.jpg
adidas39.jpg
adidas4.jpg
adidas40.jpg
adidas41.jpg
adidas42.jpg
adidas43.jpg
adidas44.jpg
adidas45.jpg
adidas46.jpg
adidas47.jpg
adidas48.jpg
adidas49.jpg
adidas5.jpg
adidas50.jpg
adidas51.jpg
adidas52.jpg
adidas53.jpg
adidas54.jpg
adidas55.jpg
adidas56.jpg
adidas57.jpg
adidas58.jpg
adidas59.jpg
adidas6.jpg
adidas60.jpg
adidas61.jpg
adidas62.jpg
adidas63.jpg
adidas64.jpg
adidas65.jpg
adidas66.jpg
adidas67.jpg
adidas68.jpg
adidas69.jpg
adidas7.jpg
adidas70.jpg
adidas8.jpg
adidas9.jpg
chanel1.jpg
chanel10.jpg
chanel11.jpg
chanel12.jpg
chanel13.jpg
chanel14.jpg
chanel15.jpg
chanel16.

AssertionError: ignored

In [20]:
#Capture the sizes of all the images...

%cd /
%cd content/drive/My\ Drive/LogoDetection/allImages

imageSizes = np.zeros((700,2))
cnt = 0

for fil in sorted(os.listdir()):
  
  assert fil.endswith('.jpg')

  img = cv2.imread(fil)
  # shape = img.shape[0]
  imageSizes[cnt] = float(img.shape[0]), float(img.shape[1]) # height -0 , widht - 1
  cnt += 1

/
/content/drive/My Drive/LogoDetection/allImages


In [24]:
#Rename all the mask files to lower case so as to maintain alphabetical ordering...
%cd /
%cd content/drive/My\ Drive/LogoDetection/allMasks

cnt = 0
for fil in sorted(os.listdir()):

  if fil.endswith('.jpg.bboxes.txt'):
    name = fil.lower()
    os.rename(fil, name)
    cnt += 1

print(cnt)
assert (cnt == 700)

/
/content/drive/My Drive/LogoDetection/allMasks
700


In [43]:
#Retrieve the paramaters of the bounding boxes and store them in labels

%cd /
%cd content/drive/My\ Drive/LogoDetection/allMasks

cnt = 0

labels = np.zeros((700, 5), dtype = 'float32')

for fil in sorted(os.listdir()):

  assert fil.endswith('.jpg.bboxes.txt')

  f = open(fil, "r")
  param = f.read().split()
  # print(fil)
  w1 = float(param[0])
  h1 = float(param[1])
  w2 = float(param[2]) + w1
  h2 = float(param[3]) + h1
  # print(float(param[3]))

  h = imageSizes[cnt][0]
  w = imageSizes[cnt][1]

  x_center = float((w1 + w2) / 2)
  x_center = float(x_center / w)

  y_center = float((h1 + h2) / 2)
  y_center = float(y_center / h)

  width = float((w2 - w1) / w)
  height = float((h2 - h1) / h)

  labels[cnt] = int((cnt // 70)), x_center, y_center, width, height

  if cnt % 70 == 0:
    print(cnt)
  cnt += 1

print(cnt)
assert (cnt == 700)

/
/content/drive/My Drive/LogoDetection/allMasks
0
70
140
210
280
350
420
490
560
630
700


In [39]:
print(labels)

[[0.         0.4053125  0.4554409  0.101875   0.14540337]
 [0.         0.7239583  0.11638734 0.16458334 0.20670392]
 [0.         0.652      0.2987805  0.172      0.17682926]
 ...
 [9.         0.40275863 0.6464531  0.36689654 0.25858122]
 [9.         0.51640624 0.41217798 0.1171875  0.06088993]
 [9.         0.48359376 0.5        0.4890625  0.25058547]]


In [48]:
#Create the text files for the bounding boxes with the correct annotations and delete the old files...
%cd /
%cd content/drive/My\ Drive/LogoDetection/allMasks

cnt = 0

for fil in sorted(os.listdir()):

  name = str(fil.split('.')[0]) + '.txt'
  # print(name)

  f = open(name, "a")

  for i in range(5):
    f.write(str(labels[cnt][i]) + " ")
    # print(labels[0][i])
  
  os.remove(fil)

  cnt += 1

print(cnt)
assert cnt == 700

/
/content/drive/My Drive/LogoDetection/allMasks
700


AssertionError: ignored